// Shared realistic call content for the demo seeds. A library of varied calls
// (distinct personas, transcripts, and coaching) so each seeded scored call opens
// like a real assessment — not the same generic transcript on every call.
//
// CALL_LIBRARY is generated by the prisma workflow "gen-demo-calls" (10 varied
// implant appointment-setting calls across low/mid/high setter performance);
// the helpers pick a band-appropriate call per session for the trend.

export type DemoCall = {
  persona: string;
  band: "low" | "mid" | "high";
  booked: boolean;
  narrative: string;
  wins: string[];
  misses: string[];
  phrases: { from: string; to: string }[];
  nextScenario: string;
  transcript: { who: "lead" | "you"; text: string }[];
};

export const CALL_LIBRARY: DemoCall[] = [
  {
    "persona": "Anxious first-timer, scared of the procedure",
    "band": "mid",
    "booked": false,
    "narrative": "Warm and genuinely reassuring with a scared first-timer, but you let the wedding-photo \"why\" and the actual outcome go unspoken, then let her steer you into \"just text me times\" instead of locking a visit.",
    "wins": [
      "Opened with real warmth and normalized her fear before anything else — 'a lot of people feel exactly that way before they even pick up the phone... you're totally normal' put her at ease fast.",
      "Asked a clean 'why now' discovery question that actually surfaced the timeline and the wedding, instead of jumping straight to scheduling.",
      "Held composure on the price hit — didn't flinch or hard-quote, and correctly pointed the exact number to the free consult and 3D scan."
    ],
    "misses": [
      "She handed you the emotional driver — noticing the gap in her daughter's wedding photos — and you never reflected it back or tied the whole call to it; the real 'why' got left on the table.",
      "You addressed fear and price but never once painted the outcome (eating normally, smiling in those photos without a second thought) before the number came up — no value frame.",
      "You closed on her terms: 'text me some times' with no specific slot offered and a husband still to consult, so nothing got booked."
    ],
    "phrases": [
      {
        "from": "would you maybe want to come take a look at what we've got?",
        "to": "I've got a Tuesday at 10 or a Thursday at 4 this week — which one's easier to get you in front of the doctor for that free scan?"
      },
      {
        "from": "Does that help a little?",
        "to": "Imagine standing in your daughter's wedding photos not thinking about that gap even once — that's exactly what this free visit is for, figuring out how we get you there."
      },
      {
        "from": "So it does depend on your case — bone, whether you need a graft, all that — which is exactly why the consult's free.",
        "to": "The best part is the consult and 3D scan are completely free, so you walk out with your exact number and zero guessing — before you decide a single thing."
      }
    ],
    "nextScenario": "Next, try a blunt price-shopper who's already got two written quotes and cuts you off the moment you mention the free consult.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi, um... so I filled out that form on your website, the one about the implant? But honestly I'm kind of freaking out even calling, so bear with me."
      },
      {
        "who": "you",
        "text": "Oh, I'm really glad you called — and hey, you'd be surprised how many people feel exactly that way before they even pick up the phone. You're totally normal. Can I get your name?"
      },
      {
        "who": "lead",
        "text": "It's Danielle. So, okay — I've got this tooth on the bottom, kind of off to the side. It cracked like a year ago and they ended up pulling it, and now there's just this gap and I keep putting off doing anything."
      },
      {
        "who": "you",
        "text": "Okay, Danielle, thank you. So it's been about a year with the gap. What's got you thinking about it now, this week specifically?"
      },
      {
        "who": "lead",
        "text": "I don't know... I guess my daughter's getting married in the spring and I keep catching it in photos. But mostly, honestly? It's the surgery. I read about them drilling into your jawbone and I almost slammed the laptop shut."
      },
      {
        "who": "you",
        "text": "Yeah, the internet will scare anybody half to death. So — the doctor numbs you all the way up first, nothing happens till you're comfortable, and a lot of our patients actually say it was easier than the extraction was. Does that help a little?"
      },
      {
        "who": "lead",
        "text": "I mean... maybe. But also I looked it up and these are what, four, five thousand dollars? For one tooth? That's a lot of money when I don't even know if I can handle the actual, you know, procedure part."
      },
      {
        "who": "you",
        "text": "So it does depend on your case — the bone, whether you'd need a graft, all of that — which is exactly why the consult's free. The doctor takes a 3D scan, walks you through everything, gives you the real number. No pressure at that visit at all."
      },
      {
        "who": "lead",
        "text": "Free is... good, I guess. I just really don't want to sit in that chair and get talked into something I'm not ready for."
      },
      {
        "who": "you",
        "text": "Totally fair, and that's not how they do it. It's really just information — you'd leave knowing your options, and honestly some people find out they need way less than they were scared of."
      },
      {
        "who": "lead",
        "text": "Okay. I'd probably want to run it by my husband too, though, before I actually schedule anything big like that."
      },
      {
        "who": "you",
        "text": "Of course. Well, whenever you're ready, we've got some openings coming up — would you maybe want to come take a look at what we've got?"
      },
      {
        "who": "lead",
        "text": "Yeah... maybe. Can you like, text me some times? And I'll talk to him and kind of figure it out."
      },
      {
        "who": "you",
        "text": "Absolutely, I can send those right over. What's the best number to reach you?"
      },
      {
        "who": "lead",
        "text": "It's the cell, the one I put on the form. Um, yeah — send them and I'll see. And thanks, really, for not making me feel dumb about being scared."
      },
      {
        "who": "you",
        "text": "You're so not dumb, Danielle — this is a big deal and you're already doing great just by looking into it. I'll get those times over to you. Talk soon, okay?"
      }
    ]
  },
  {
    "persona": "Price-first, guarded shopper",
    "band": "low",
    "booked": false,
    "narrative": "You let the lead steer the whole call onto price, quoted a range you never should have, and never uncovered why chewing again mattered — so it drifted into a \"maybe.\"",
    "wins": [
      "Stayed friendly and didn't get defensive when the lead threw the competitor's $3,200 quote at you.",
      "Were honest that implants usually aren't covered by insurance instead of overselling a benefit that isn't there.",
      "Planted a seed of value by calling it 'an investment that lasts a long time' — the instinct was right, just too late and too thin."
    ],
    "misses": [
      "You quoted a price range ('three-and-a-half to five thousand') — as a coordinator that's not your call to make, and it anchored the entire conversation on cost.",
      "The lead told you they hadn't chewed on the right side in months, and you jumped straight to emailing a price sheet instead of exploring what living like that has been costing them.",
      "You closed on 'call back' and 'maybe' — no specific consult times, so nothing got locked in."
    ],
    "phrases": [
      {
        "from": "a single implant with the crown, it's usually somewhere around three-and-a-half to five thousand? But honestly the doctor would have to look.",
        "to": "Honestly? The doctor sets that after a quick look, because it comes down to the tooth and the bone underneath. That exam's free, and you'd walk out with the exact number instead of a guess. Can I grab you a time this week?"
      },
      {
        "from": "do you want me to send you some information? Like a price sheet or something?",
        "to": "It sounds like just being able to chew on that side again is the real goal here — and months is a long time to go without. Let's get you in front of the doctor so you know exactly what it'd take. I've got Thursday at 2 or Friday morning — which is easier?"
      },
      {
        "from": "you can call back and we can find a time for a consult. It's free.",
        "to": "Let's lock it in right now while we're on the phone — the consult's free and there's zero pressure to move forward. Does tomorrow at 10 or 3:30 work better for you?"
      }
    ],
    "nextScenario": "Next, take a lead who already has a written quote from another office and pushes you to price-match on the spot.",
    "transcript": [
      {
        "who": "lead",
        "text": "Yeah, hi — I'm calling about the implant thing. Just tell me straight, how much am I looking at for one tooth?"
      },
      {
        "who": "you",
        "text": "Oh — um, hi! Thanks for calling in. So it kind of depends, implants can range quite a bit depending on—"
      },
      {
        "who": "lead",
        "text": "That's exactly what everybody says. Ballpark me. I've already called two other places today."
      },
      {
        "who": "you",
        "text": "Right, totally fair. I mean, a single implant with the crown, it's usually somewhere around three-and-a-half to five thousand? But honestly the doctor would have to look."
      },
      {
        "who": "lead",
        "text": "See, that's a lot. The place down the road quoted me thirty-two hundred, all in."
      },
      {
        "who": "you",
        "text": "Yeah, we're... you know, competitive. We do really good work here."
      },
      {
        "who": "lead",
        "text": "Everybody says they do good work. What actually makes you different, besides being more expensive?"
      },
      {
        "who": "you",
        "text": "Um — well, our dentist has done a ton of these. Like, a lot. Patients are really happy."
      },
      {
        "who": "lead",
        "text": "Okay. And is any of this covered? I've got a Delta plan through work."
      },
      {
        "who": "you",
        "text": "Implants themselves usually aren't covered, unfortunately. Sometimes a little bit toward the crown, but I really wouldn't count on it."
      },
      {
        "who": "lead",
        "text": "Perfect. So I'm paying full freight for one tooth."
      },
      {
        "who": "you",
        "text": "I hear you. It's an investment though — it lasts a long time, so."
      },
      {
        "who": "lead",
        "text": "Look... I just wanna be able to chew on the right side again. It's been like five months since I lost it, I'm doing everything on one side. But not for five grand, I can't swing that."
      },
      {
        "who": "you",
        "text": "Yeah, no, that makes total sense. Um — do you want me to just send you some info? Like a price sheet or something you can look over?"
      },
      {
        "who": "lead",
        "text": "I guess. Email it, sure."
      },
      {
        "who": "you",
        "text": "Okay cool. And, I mean, whenever you're ready you can call back and we'll find a time for a consult — it's free, so."
      },
      {
        "who": "lead",
        "text": "Yeah... maybe. Let me think about it."
      },
      {
        "who": "you",
        "text": "For sure, no worries at all. Have a good one!"
      }
    ]
  },
  {
    "persona": "Busy sales exec, decisive",
    "band": "high",
    "booked": true,
    "narrative": "Jordan read the room fast, respected Marcus's tight clock, dug past the cracked molar to the real driver — feeling like himself at client dinners — and closed cleanly on a specific time before his travel window.",
    "wins": [
      "Respected his 10-minute clock right away and still built warmth — grabbed his name and promised to be quick and 'get you what you need,' so a rushed lead didn't feel processed.",
      "Uncovered the real 'why' instead of stopping at the tooth — the question 'is it the discomfort, or something else driving the timing?' opened up the travel, the client dinners, and 'feeling like an old man' at 44.",
      "Held composure on the price jab, refused to hard-quote, and reframed the consult as 'the one visit that saves you visits,' then closed on two concrete times built around his travel."
    ],
    "misses": [
      "Value framing drifted slightly generic ('functions like your own tooth') right after he'd handed over a vivid why — the client dinners and chewing on one side — that could have been mirrored back word-for-word.",
      "Named financing but never anchored even a rough monthly range, so his 'five, six grand a tooth' sticker was deflected rather than defused before the close.",
      "Promised to text the address without first confirming the best cell number to reach him on."
    ],
    "phrases": [
      {
        "from": "a single implant is exactly the fix for that — it's a permanent replacement that functions like your own tooth",
        "to": "Picture your next client dinner — chewing on both sides, not babying it, not thinking about it. That's the thing a single implant hands back to you."
      },
      {
        "from": "I can't quote you a real number over the phone without the doctor seeing the scan",
        "to": "I won't guess at your number, but single-implant plans sit in a range we can finance into a low monthly — the doctor confirms your exact figure Thursday, no surprises."
      },
      {
        "from": "I'll text you the address and a link to fill out the quick health history",
        "to": "What's the best cell to reach you on? I'll text the address and a 2-minute health form so you skip the clipboard when you land."
      }
    ],
    "nextScenario": "Next, run a spouse-gatekeeper who warms up on discovery but stalls at the close with 'I really can't book anything until I run it past my wife,' and won't hold a time.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hey — yeah, I filled something out on your site last night about an implant? Sorry, I'm kinda squeezed between meetings, so I've got maybe ten minutes, tops."
      },
      {
        "who": "you",
        "text": "No problem at all, I'll be quick and get you exactly what you need. I'm Jordan, treatment coordinator here — can I grab your first name?"
      },
      {
        "who": "lead",
        "text": "It's Marcus."
      },
      {
        "who": "you",
        "text": "Good to meet you, Marcus. So — you mentioned an implant. What's going on, what made you reach out?"
      },
      {
        "who": "lead",
        "text": "Cracked an upper molar a few months back. Got a crown on it, the thing failed again, and now the tooth's basically done. My dentist says it's gotta come out. I've just been putting it off, and honestly I'm sick of it — I want it handled."
      },
      {
        "who": "you",
        "text": "Okay, so you've already been through a crown that didn't hold, and now you're looking at pulling it and replacing it — after already spending the time and money once. That's genuinely frustrating. When you say you want it handled, is it mostly the discomfort, or is something else driving the timing?"
      },
      {
        "who": "lead",
        "text": "Honestly? It's the eating. I'm chewing on one side, it throbs when I fly — and I fly basically every week for work. I run sales, I'm in client dinners constantly, and I'm sitting there favoring one side like an old man. I'm 44. I'm just done with it."
      },
      {
        "who": "you",
        "text": "That makes complete sense — so it's not really about a tooth, it's showing up in the parts of your life that matter: the travel, the dinners, feeling like yourself in front of clients. The good news is a single implant is exactly the fix for that — it's a permanent replacement that functions like your own tooth, so you're back to chewing on both sides and not thinking about it. The consult is where our doctor does a 3D scan, confirms the plan, and gives you an exact timeline and number for your case."
      },
      {
        "who": "lead",
        "text": "Yeah, that's the part. My buddy told me implants run like five, six grand a tooth. And my calendar is insane — I don't have time to come in three separate times just to talk about it."
      },
      {
        "who": "you",
        "text": "Both fair. On cost — every case is different, so I can't quote you a real number over the phone without the doctor seeing the scan, but you'll walk out of the consult with the exact figure and the financing options laid out, no surprises. And on time — the consult is the one visit that saves you visits. It's about 45 minutes, all in one stop: exam, 3D scan, your plan. We build the schedule around your travel, not the other way around. Are you in town at all this week?"
      },
      {
        "who": "lead",
        "text": "I'm actually home Thursday and Friday, then I'm gone the following two weeks."
      },
      {
        "who": "you",
        "text": "Perfect — let's grab you before you travel. I've got Thursday at 8:15 in the morning, get it knocked out before your day even starts, or Friday at 4:30 if the afternoon's easier. Which one works?"
      },
      {
        "who": "lead",
        "text": "Thursday early. 8:15's good."
      },
      {
        "who": "you",
        "text": "Done — Thursday at 8:15, I've got you locked in, Marcus. I'll text you the address and a link to fill out the quick health history so you're not stuck with paperwork when you walk in. Plan for about 45 minutes, and you'll leave with the plan, the number, and the timeline — the whole picture."
      },
      {
        "who": "lead",
        "text": "Sounds great. Appreciate you making that easy — see you Thursday."
      }
    ]
  },
  {
    "persona": "Skeptical comparison shopper (quoted cheaper elsewhere)",
    "band": "mid",
    "booked": true,
    "narrative": "Composed, likeable call — you cleverly exposed the cheaper quote as apples-to-oranges and closed on a specific time, but you skated past his real \"why\" and booked him on logic instead of the outcome he actually wants back.",
    "wins": [
      "Neutralized the $1,100 quote without trash-talking the competitor — you asked whether it included the crown and abutment ('that's usually where the numbers get funny'), reframing him from price-shopping to comparing the same thing.",
      "Strong composure on his upsell fear — 'if the other place really is cheaper all-in, I'll be the first to tell you to go take it' dropped the pressure and earned trust instead of arguing.",
      "Clean close: two concrete options (Thursday 10:40 or Tuesday 5:15), locked the booking, and set up a reminder text plus 'bring the other quote' to make the consult stick."
    ],
    "misses": [
      "You let the real why slide right by — he told you his wife's on him and he's chewing on one side, and you jumped straight into price mechanics instead of exploring how six months of that has actually been wearing on him.",
      "Value never got framed before the number — you explained how the consult works but never painted what getting the tooth back does for him, so the whole call stayed a conversation about dollars.",
      "Discovery stayed surface-level — you never quantified the impact (eating out, avoiding certain foods, self-consciousness), so at close you had nothing but price and logistics to lean on."
    ],
    "phrases": [
      {
        "from": "Totally fair. So real quick — when they quoted you the eleven, did that include the crown and the abutment, or was that just the post itself?",
        "to": "Yeah — and it sounds like this has been nagging at you for a bit, chewing on one side, your wife on your case. Before we even get to price, let me make sure they quoted you the same thing: did that eleven hundred include the crown, or just the post?"
      },
      {
        "from": "That's exactly why we do the consult first — the doc looks at it, you get one all-in number in writing before you commit to anything.",
        "to": "Here's what matters more than the sticker, Darren — this is a tooth you'll chew on every day for the next twenty years. The consult gets you one all-in price in writing AND confirms it'll actually last, so you're not paying twice in three years."
      }
    ],
    "nextScenario": "Next, take on a spouse-blocker who's sold on the treatment but insists 'I can't book anything until I run it past my wife' and won't give you a real timeline.",
    "transcript": [
      {
        "who": "lead",
        "text": "Yeah, hi — I'm calling around on implants. A place across town quoted me like eleven hundred bucks for a single one, and your site didn't list any prices, so I figured I'd see what you guys run before I book anything."
      },
      {
        "who": "you",
        "text": "Hey, thanks for calling in! Yeah, no problem, I can walk you through how we handle it. Can I grab your name real quick?"
      },
      {
        "who": "lead",
        "text": "It's Darren."
      },
      {
        "who": "you",
        "text": "Good to meet you, Darren. So it's a single tooth you're looking at — is it one that's already out, or one that's failing?"
      },
      {
        "who": "lead",
        "text": "It's out. Bottom, kinda toward the back. Been gone maybe six months now. I've just been putting it off, honestly."
      },
      {
        "who": "you",
        "text": "Gotcha. And what's got you looking into it now, after six months?"
      },
      {
        "who": "lead",
        "text": "Eh — my wife's been on me about it. And I've started chewing on just one side, which is getting old. But mostly I just want the best price. That eleven hundred sounded pretty good to me."
      },
      {
        "who": "you",
        "text": "Totally fair. So real quick — when they quoted you the eleven, did that include the crown and the abutment, or was that just the post itself? 'Cause that's usually where the numbers get funny."
      },
      {
        "who": "lead",
        "text": "...Honestly? I don't know. They just said eleven hundred for the implant."
      },
      {
        "who": "you",
        "text": "Right, and that's the thing — a lot of times that number's just the fixture, and then the crown's billed separate, so folks show up thinking one price and it ends up two or three. That's exactly why we do the consult first — the doc looks at it, you get one all-in number in writing before you commit to anything."
      },
      {
        "who": "lead",
        "text": "See, but that's kinda what worries me. I feel like once I'm sitting in the chair you people just talk me into the expensive version."
      },
      {
        "who": "you",
        "text": "I hear you, and honestly — zero pressure. The consult's free, and if that other place really is cheaper all-in, I'll be the first to tell you to go take it. We just want you comparing apples to apples instead of guessing."
      },
      {
        "who": "lead",
        "text": "Okay. Yeah, that's fair, I guess."
      },
      {
        "who": "you",
        "text": "And the nice part is the doc does a quick scan that day, so you actually know the bone's still solid back there — because after six months there's sometimes a little going on, and that can move the price more than which office you pick."
      },
      {
        "who": "lead",
        "text": "Huh. Yeah, I hadn't even thought about that."
      },
      {
        "who": "you",
        "text": "So let me get you in. I've got a Thursday at 10:40 in the morning, or if evenings are easier there's a Tuesday at 5:15 — which one works better for you?"
      },
      {
        "who": "lead",
        "text": "Uh... let's do the Thursday. The 10:40."
      },
      {
        "who": "you",
        "text": "Perfect — Thursday at 10:40, you're booked, Darren. I'll text you the address and a reminder. Bring that other quote if you've got it in writing, makes the comparison way easier."
      }
    ]
  },
  {
    "persona": "Needs spouse to approve first",
    "band": "mid",
    "booked": false,
    "narrative": "Warm, composed call that surfaced the missing molar and handled the price scare without flinching, but the setter never deepened the emotional why and let a spouse-approval exit end the call without ever offering a single specific consult time.",
    "wins": [
      "Disarmed the lead instantly — 'not crazy at all, I'm really glad you called' — and dropped the pressure so she opened up about the two-year gap.",
      "Held composure on the price scare: didn't flinch at the neighbor's '$9 grand,' redirected cleanly to the free consult and 'more workable than the scary figure you heard.'",
      "Named it as a two-person decision and invited the husband to the consult instead of arguing against him."
    ],
    "misses": [
      "Never put a single specific time on the table — accepted 'I'll call you back' and offered to text info instead of booking.",
      "Let the emotional why stay shallow: got to 'miss eating a steak' and a clicking jaw but never dug into how the gap actually affects her daily.",
      "Dropped the 'bring him to the consult' idea the moment she hesitated, instead of anchoring a time that worked around his schedule."
    ],
    "phrases": [
      {
        "from": "why don't I send you some info by text, and you can chat with him?",
        "to": "Let's do this — I've got Tuesday at 5:30 or Saturday at 9, both after work so he can come too. Which one gets you both in front of the doctor?"
      },
      {
        "from": "I don't want to rush you. The consult itself is free and there's no obligation...",
        "to": "Since it's free and there's zero obligation, the smart move is to grab a spot now — you can always move it. That way you two decide with the real number, not the nine grand your neighbor heard."
      },
      {
        "from": "So if we could get that side working again — that'd be the goal?",
        "to": "Two years chewing on one side and now the jaw's clicking — what's that been like day to day? What are you avoiding that you'd love to just do again without thinking?"
      }
    ],
    "nextScenario": "A blunt, time-pressed lead who already has a cheaper quote from another office and cuts you off every time you mention the consult.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi — yeah, I put my info in on your website last night, the implant thing? I almost didn't call back, honestly. My husband thinks I'm a little crazy for even looking into it."
      },
      {
        "who": "you",
        "text": "Oh, not crazy at all — I'm really glad you called. I'm Dana, I help folks sort out the implant side of things before they ever sit in the chair, so there's zero pressure on this call. What got you looking in the first place?"
      },
      {
        "who": "lead",
        "text": "Well, I've got a back tooth — a molar, I think — that cracked a couple years ago. They ended up pulling it and I just... left the gap. And now it's kind of bugging me."
      },
      {
        "who": "you",
        "text": "Okay, so a molar came out and the gap's been sitting there about two years. Is it more the discomfort now, or something else pushing you?"
      },
      {
        "who": "lead",
        "text": "Both, I guess. Mostly I can't chew on that side at all. I've been eating on one side this whole time and now the jaw sort of clicks when I open it."
      },
      {
        "who": "you",
        "text": "Yeah, that one-sided chewing catches up with people. So if we could get that side working again — that's really the goal?"
      },
      {
        "who": "lead",
        "text": "That'd be huge. I miss just eating a steak without planning around it, you know? But I'll be straight with you — it's the price that scares me. My neighbor said hers ran like nine grand."
      },
      {
        "who": "you",
        "text": "I hear that number a lot, and I get it. Every mouth's different so I can't give you an exact figure over the phone — that's actually the whole point of the free consult. They scan it, you get a real plan with the real number, and honestly a lot of people find it's more workable than the scary figure they walked in with."
      },
      {
        "who": "lead",
        "text": "Okay, that's fair. But see, here's my thing — I can't just say yes to something like this. My husband and I decide the big stuff together, and he's... he's not sold yet."
      },
      {
        "who": "you",
        "text": "That makes complete sense — this is a two-person call. Would it help if he came to the consult with you? That way you're both hearing the exact same thing from the doctor instead of me relaying it."
      },
      {
        "who": "lead",
        "text": "Maybe. He works a ton though. Honestly I think I just need to sit down and talk to him before I go scheduling anything."
      },
      {
        "who": "you",
        "text": "Sure, I don't want to rush you. The consult itself is free and there's no obligation, so a lot of people book it just to have the info to bring home."
      },
      {
        "who": "lead",
        "text": "Yeah... I think I'd rather run it by him first and then call you back once I know where his head's at."
      },
      {
        "who": "you",
        "text": "Totally understand. Tell you what — why don't I send you some info by text so you've got it, and you can chat with him? I'm right here if any questions come up."
      },
      {
        "who": "lead",
        "text": "That works. Thank you, Dana — I really appreciate you not pushing me on it."
      },
      {
        "who": "you",
        "text": "Of course. Talk to him, and just give me a call whenever you two are ready — I'll get you both in."
      }
    ]
  },
  {
    "persona": "Adult son researching implants for his elderly dad",
    "band": "high",
    "booked": true,
    "narrative": "A warm, patient call where the setter got past the dentures to the real reason — dad pulling away from Sunday family dinners — calmed the \"is he too old\" fear, and locked a specific Saturday morning slot.",
    "wins": [
      "Dug past the mechanical complaint and surfaced the real why — that Ray had quietly stopped coming to the family's Sunday dinners since losing his wife — then named it back to Marcus instead of steamrolling to booking.",
      "Handled the 'he's 78, is he even a candidate' fear with composure, reframing the visit as a free health screening and 3D scan that gives a real answer either way, no hard sell.",
      "Closed on two concrete options (Thursday 2:40 or Saturday 9:20), read the 'he's sharper in the mornings' cue, and confirmed the exact slot back."
    ],
    "misses": [
      "Promised to text prep and parking but never actually captured or confirmed Marcus's cell number, or clarified who should get Ray's reminders.",
      "Didn't nail down who's attending or making the decision — is Marcus coming with Ray, and is Ray on board with the visit at all?",
      "Left momentum on the table by not tying the timeline to anything concrete (an upcoming birthday, holiday, or the next Sunday dinner) to make booking feel urgent rather than open-ended."
    ],
    "phrases": [
      {
        "from": "So tell me a little about what's going on with Ray's dentures — what's not working?",
        "to": "Before we even get into the teeth — what made today the day you finally picked up the phone for him?"
      },
      {
        "from": "Can I get your name?",
        "to": "Who am I talking with — and who are we getting those permanent teeth for?"
      },
      {
        "from": "I'll text you the scan prep and parking info.",
        "to": "What's the best cell for the prep and parking details — and should Ray get his reminders at that number too, or a different one?"
      }
    ],
    "nextScenario": "A skeptical adult daughter who opens cold with 'just give me your price for full mouth implants' and refuses to answer any questions until you name a number.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi, yeah — I'm actually calling for my dad. I saw your ad, the permanent teeth thing? He's got dentures and they're just... not working out. Figured I'd do the legwork since he won't."
      },
      {
        "who": "you",
        "text": "Oh, I love that you're doing this for him — honestly most folks won't even pick up the phone for themselves, so it's great he's got you in his corner. Who am I talking with — and who are we getting those permanent teeth for?"
      },
      {
        "who": "lead",
        "text": "It's Marcus. It's for my dad, Ray — he's 78."
      },
      {
        "who": "you",
        "text": "Marcus, nice to meet you. So tell me a little about what's going on with Ray's dentures — what's not working for him?"
      },
      {
        "who": "lead",
        "text": "They slip. They click when he talks. He's had 'em relined like twice and a few months later it's the same thing. He just kinda deals with it, you know? But I can tell it bugs him."
      },
      {
        "who": "you",
        "text": "Yeah — reline after reline and it never really holds, that's such a common story with the lowers especially. When you say you can tell it bugs him... what's that look like day to day?"
      },
      {
        "who": "lead",
        "text": "Honestly? He stopped eating with us. We do Sunday dinners, the whole family, and the last few months he eats before he comes over or says he's not hungry. My mom passed two years ago and Sundays were kind of their thing, so... yeah. It's not really about the teeth."
      },
      {
        "who": "you",
        "text": "Marcus... I'm really glad you told me that. So it's not the dentures, is it — it's that he's pulling back from the table, from all of you. That's the part that actually matters here."
      },
      {
        "who": "lead",
        "text": "Exactly. I don't care what it costs to fix the teeth, I just want him back at the table. But — okay, real talk. Is he even a candidate? He's 78, he's got some blood pressure stuff. I don't wanna drag him in and get his hopes up for a no."
      },
      {
        "who": "you",
        "text": "That's the exact right question, and it's honestly what the consult is for. The doctor does a full health screening and a 3D scan before anyone even talks treatment — age by itself is almost never the dealbreaker, it's more about bone and overall health, and a lot of our implant patients are in their seventies and eighties. If he's not a fit, you'll leave knowing that, for free, no hard sell. Either way you get a real answer instead of a guess."
      },
      {
        "who": "lead",
        "text": "Okay. That's fair. And cost — ballpark? I don't wanna walk in totally blind."
      },
      {
        "who": "you",
        "text": "Totally fair to ask, and I won't dodge you — but I genuinely can't give you a real number over the phone, and I wouldn't trust anyone who did, because it swings a lot on Ray's scan, whether it's a few implants or a full arch. What I can promise: the consult's free, they lay out the exact options and the numbers in writing, and there's financing that breaks it monthly if that helps. Would it take the pressure off if he just came, got the actual plan, and then you two decide together — no commitment?"
      },
      {
        "who": "lead",
        "text": "Yeah. That actually — yeah, let's do that."
      },
      {
        "who": "you",
        "text": "Love it. I've got two good spots for a first visit — Thursday at 2:40, or if mornings are easier on him, Saturday at 9:20. Which one works better for Ray?"
      },
      {
        "who": "lead",
        "text": "Saturday's better. He's sharper in the mornings. Let's do the 9:20."
      },
      {
        "who": "you",
        "text": "Perfect — Saturday at 9:20 for Ray. I'll block a little extra so nobody's rushing him. He's lucky to have you on this, Marcus."
      }
    ]
  },
  {
    "persona": "Embarrassed long-avoider",
    "band": "high",
    "booked": true,
    "narrative": "A genuinely warm, well-paced call — Dana came in ashamed and left booked because the setter found the real 'why' (the son's May wedding) and anchored the whole appointment to it instead of the price.",
    "wins": [
      "Surfaced the true emotional driver by asking 'why now?' — got Dana past 'my teeth' to 'I don't want to be the guy in the back of every wedding photo,' which is the real booking fuel.",
      "Framed value before any number and refused to hard-quote — 'This was never really about teeth' plus honestly declining to guess a price over the phone kept confidence high and protected the consult.",
      "Closed on two specific times (Thursday 2:15 or Tuesday 9:30), got a commitment, and locked it with reassurance about being walked straight back."
    ],
    "misses": [
      "Right after Dana's most vulnerable moment ('I'm nervous... horror stories'), the setter launched into a long two-part answer instead of pausing to name the fear back for a beat first.",
      "Said 'I'll text you the address' but never actually confirmed Dana's cell number on the call — a small logistics gap that quietly raises no-show risk.",
      "Leaned on 'the consult itself is free' inside the close; leading with free can subtly cheapen the visit when the wedding-photo outcome was the stronger anchor to ride out alone."
    ],
    "phrases": [
      {
        "from": "That's fair, and I'd rather you say it than sit on it. So two things.",
        "to": "That's fair — and honestly, being nervous about this is the most normal thing in the world. Let's just take it one piece at a time."
      },
      {
        "from": "and the consult itself is free. You'd leave knowing exactly where you stand, zero pressure.",
        "to": "You'd walk out with a real plan to be in every one of those May photos — that's what you're coming for. And there's no charge for the visit itself."
      },
      {
        "from": "I'll text you the address and I'll be the one who meets you at the door, okay?",
        "to": "What's the best cell to text the details to? I'll send the address right now so it's locked in, and I'll be the one meeting you at the door."
      }
    ],
    "nextScenario": "Next, try a spouse-blocker who warms up but says 'I really have to run this by my wife first' and won't commit to a time until you've handled the second decision-maker.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi — um, I saw something online about implants and I just... honestly I don't even really know why I'm calling. I've kind of been avoiding this for a long time."
      },
      {
        "who": "you",
        "text": "Hey, I'm really glad you did. Most people who call me open with almost that exact line — that they've put it off. There's zero judgment on this end. Can I grab your name so I'm not just calling you 'you' the whole time?"
      },
      {
        "who": "lead",
        "text": "It's Dana. And yeah... it's been years. A couple of my front teeth are basically gone, and the rest aren't great. I've kind of stopped smiling in pictures altogether."
      },
      {
        "who": "you",
        "text": "Dana, thank you for saying that out loud — I know it's not the easiest thing to admit to a stranger. When you say years, are we talking a couple, or longer?"
      },
      {
        "who": "lead",
        "text": "Longer. Probably seven, eight years since I really did anything. I kept telling myself I'd deal with it later, and, you know... later just never showed up."
      },
      {
        "who": "you",
        "text": "I hear that all day, so you're in good company. Can I ask you the real question though — after all that time, why now? What made today the day you actually picked up the phone?"
      },
      {
        "who": "lead",
        "text": "My son's getting married in May. They sent around these save-the-date photos they're planning, and I just... I don't want to be the guy in the back with his mouth shut in every single shot. I want to actually be in it. With my grandkids and everything."
      },
      {
        "who": "you",
        "text": "Okay — that right there is the whole thing, Dana. This was never really about teeth. It's about standing in your son's wedding photos in May and not thinking about your mouth for one second. That's exactly what a consult is built to map out — what it'd actually take to get you there by then, laid out plain."
      },
      {
        "who": "lead",
        "text": "Yeah. I mean... okay, but I'll be honest, I'm nervous. I've read some horror stories online, and I don't even know what something like this costs. I'm scared it's gonna be some crazy number and I've wasted everybody's time."
      },
      {
        "who": "you",
        "text": "That's fair, and I'd rather you say it than sit on it. So two things. Those scary stories online are almost never a real plan — they're people who guessed. And on cost: I'm not the doctor, so I won't throw a number at you over the phone and I wouldn't do that to you anyway. The consult gets you the actual options for your mouth, including ways to space the investment out, so you're deciding with facts instead of fear. And the visit itself is free — you'd leave knowing exactly where you stand, no pressure."
      },
      {
        "who": "lead",
        "text": "Okay. That actually helps. The free part helps too, not gonna lie. I think I could do that. I just don't want to sit in a waiting room feeling like the whole place is staring at my teeth."
      },
      {
        "who": "you",
        "text": "You won't — I'll walk you straight back myself, and the doctor has genuinely seen every version of this a thousand times. Let's just get you in. I've got a Thursday at 2:15, or if mornings are easier on you, a Tuesday at 9:30. Which one fits your week better?"
      },
      {
        "who": "lead",
        "text": "Uh... Tuesday morning. The 9:30. I'd rather just get it over with early in the day."
      },
      {
        "who": "you",
        "text": "Tuesday at 9:30 — done, I'm putting your name on it right now, Dana. Bring nothing but yourself, and honestly, come in thinking about May, because that's what we're solving for. I'll text you the address and I'll be the one who meets you at the door, okay?"
      },
      {
        "who": "lead",
        "text": "Okay. Thank you — really. I feel a lot better than I did five minutes ago."
      }
    ]
  },
  {
    "persona": "Insurance-focused; assumes \"50% major services\" should cover the implant",
    "band": "mid",
    "booked": false,
    "narrative": "Solid discovery and calm on the insurance objection, but she left the daughter's-wedding \"why\" untouched and closed on the lead's terms instead of offering times, so it never booked.",
    "wins": [
      "Paused the pricing question to open discovery first — 'can I ask what's going on with the partial? You said you hate it' — which surfaced the slipping partial and how it's stealing her lunches with friends.",
      "Handled the '50% major services' objection with composure and specifics (implants often carved out, benefits paid toward the crown not the post, the ~$1,500-2,000 annual max) without ever promising coverage that isn't real.",
      "Held firm on price when pushed for a ballpark — declined to guess a number that could be wrong 'in either direction' and re-anchored to the free consult and exam."
    ],
    "misses": [
      "Heard the two biggest emotional signals — 'I don't smile in pictures anymore' and 'my daughter's getting married in the spring' — and let them slide by; the real why was handed to her and never mirrored back or used to build urgency.",
      "Closed on the lead's terms ('call us back whenever you're ready') with no specific consult times offered, so the call ended with no appointment and no reason for her to act now.",
      "Value showed up late and thin ('you just... live') and only after the cost talk had already started — the outcome (smiling at the wedding, eating without watching every bite) was never painted before the number."
    ],
    "phrases": [
      {
        "from": "Why don't you talk it over and give us a call back whenever you're ready and we'll find you a time?",
        "to": "It totally makes sense to loop your husband in — most couples decide this together. The consult's free and there's no obligation, so let's just hold a spot you can move if you need to: I've got Tuesday at 10 or Thursday at 4 — which one's easier?"
      },
      {
        "from": "The wedding, yeah. Okay. So we'd definitely want to get you comfortable well before then.",
        "to": "Your daughter's wedding in the spring — I want you smiling in every one of those photos, not hiding behind a closed mouth. Let's make sure you're fully settled long before that day. When is it?"
      },
      {
        "from": "the implant's the one that doesn't slip, doesn't come out, you just... live.",
        "to": "Picture lunch with the girls where the partial never crosses your mind — you just eat, laugh, and talk. That's what the implant gives back, and it's why people tell us it's the last time they ever deal with this."
      }
    ],
    "nextScenario": "A skeptical husband joins the call, demands an exact out-the-door price before agreeing to anything, and dismisses \"free consult\" as a sales tactic.",
    "transcript": [
      {
        "who": "lead",
        "text": "Yeah, hi — I'm calling about the implants. I've got a partial on the bottom I can't stand, and honestly before I do anything I just need to know what my insurance is gonna pay. That's really my whole question."
      },
      {
        "who": "you",
        "text": "Totally fair — nobody wants to guess on cost. I'm Dana, by the way, I help folks get set up here. Before we get into the insurance piece, can I ask what's going on with the partial? You said you can't stand it —"
      },
      {
        "who": "lead",
        "text": "It slips. Like I'll be out at lunch with the girls and I feel it shift and I just... stop talking. I've had it three years and it's never once fit right."
      },
      {
        "who": "you",
        "text": "Ugh, that sounds exhausting — feeling like you've gotta watch every single bite. So it's on the lower — do you know how many teeth the partial's replacing?"
      },
      {
        "who": "lead",
        "text": "Two on one side, one on the other. But it's the one kind of toward the front that shows. I don't even smile in pictures anymore. And my daughter's getting married in the spring, so—"
      },
      {
        "who": "you",
        "text": "The wedding, yeah. Okay. So we'd definitely want to get you comfortable well before then. Let me pull up the insurance side — I'll be straight with you, most dental plans will chip in something toward implants but they don't cover it the way they'd cover a filling."
      },
      {
        "who": "lead",
        "text": "See, that's the part I don't get. I pay every month. My plan literally says 'major services, fifty percent.' An implant's major, right? So it should be half."
      },
      {
        "who": "you",
        "text": "That's a really fair read, and a lot of plans do say fifty percent on major. The catch is a lot of them carve implants out specifically, or they'll pay toward the crown but not the implant post — and then there's usually an annual max, something like fifteen hundred to two grand, that caps the whole year. The honest answer is I can't give you your real number over the phone without seeing the actual plan."
      },
      {
        "who": "lead",
        "text": "So basically you're telling me I'm paying for the whole thing."
      },
      {
        "who": "you",
        "text": "Not necessarily — whatever your plan does pay, we apply every dollar of it. And the reason folks still go for it is the implant's the one that doesn't slip, doesn't come out at night, you just... live. It's a totally different thing than the partial. What we'd do is a free consult where the doctor takes a look and our coordinator runs your actual benefits and gives you the real number plus payment options, all in one visit, no charge."
      },
      {
        "who": "lead",
        "text": "Hmm. And how much roughly, though? Just a ballpark, so I'm not walking in and fainting."
      },
      {
        "who": "you",
        "text": "I hear you. I really can't give you a real ballpark because it depends on what the doctor sees — the bone, whether you'd need anything else first — and I'd hate to throw out a number that's wrong in either direction. That's genuinely what the consult's for, and it doesn't cost you anything."
      },
      {
        "who": "lead",
        "text": "Okay. Let me think on it and probably check with my husband about the money."
      },
      {
        "who": "you",
        "text": "Yeah, of course, no pressure at all. Talk it over, and give us a call back whenever you're ready and we'll find you a time."
      },
      {
        "who": "lead",
        "text": "Sure. I'll probably call back. Thanks for the info."
      },
      {
        "who": "you",
        "text": "Of course — thanks for calling, talk soon!"
      }
    ]
  },
  {
    "persona": "Ready-to-book, timeline-driven",
    "band": "high",
    "booked": true,
    "narrative": "A confident, warm call where Renee mined the real \"why\" (April wedding photos), stayed unshaken on the $40k website number by pivoting to the free scan, and closed on two travel-friendly times.",
    "wins": [
      "Instead of jumping straight to scheduling, Renee asked \"what finally pushed you to fill that out last night?\" and uncovered the emotional driver early.",
      "She surfaced and anchored to the real why - the daughter's April wedding photos - then tied the entire close back to it (\"that's exactly what we're building toward\").",
      "She handled the $40k website number with total composure, refusing to quote and reframing to \"your number, not the internet's number\" from a free 3D scan."
    ],
    "misses": [
      "Never asked for or used the lead's name - booked and confirmed the whole appointment without personalizing it once.",
      "Didn't reassure her on whether April is actually achievable given possible grafting/healing, leaving a small timeline gap on the thing she cared about most."
    ],
    "phrases": [
      {
        "from": "Love that energy - and good morning! I'm Renee, I'm the treatment coordinator here.",
        "to": "Good morning! I'm Renee, one of the treatment coordinators - and I love that you're ready to move; my whole job is making the timing actually work around your life."
      },
      {
        "from": "Perfect. Monday at 4:30 it is - and hey, tuck that April date in the back of your mind.",
        "to": "Perfect - and I never caught your name, what should I put on the appointment? ...Great, Monday at 4:30, Susan; that April date is exactly what we're building toward."
      },
      {
        "from": "It's about an hour - scan, sit with the doctor, walk out with your plan and your number.",
        "to": "It's about an hour - scan, meet the doctor, and you'll walk out knowing exactly whether April's realistic and what it takes to get there."
      }
    ],
    "nextScenario": "Next, try a skeptical spouse who is the decision-maker and refuses to book anything until you give a hard, exact price over the phone.",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi, yeah - I filled out that form last night about the full set of implants up top. I'm kind of ready to just do this, I mostly need to know how fast we can get it going."
      },
      {
        "who": "you",
        "text": "Good morning! I'm Renee, one of the treatment coordinators here. I love that you're ready to move - before we map out timing, can I ask what finally pushed you to fill that out last night?"
      },
      {
        "who": "lead",
        "text": "Honestly? My top denture. I've had it about three years and it clicks when I talk. I do a lot of client dinners and I'm just... done being self-conscious about it."
      },
      {
        "who": "you",
        "text": "Yeah - that click at dinner is the worst, because it's the exact moment you want to not be thinking about your mouth. How long have you been kind of pushing through that?"
      },
      {
        "who": "lead",
        "text": "Too long. Probably a solid year of just avoiding it. So yeah, timeline's my big thing - I travel Tuesday through Thursday most weeks."
      },
      {
        "who": "you",
        "text": "Got it, so we build this around a travel schedule. Quick question - when you picture this being done, is there a date you're aiming for? Sometimes there's a trip, an event..."
      },
      {
        "who": "lead",
        "text": "My daughter's getting married in the spring. April. I do not want to be in some temporary flipper in the photos."
      },
      {
        "who": "you",
        "text": "Okay - so that's the real deadline. April, in the photos, smiling wide and not thinking about your teeth once. That's very doable. Can I be straight with you on how the timeline actually works?"
      },
      {
        "who": "lead",
        "text": "Please. And - I'll just say it - I saw a number online, around forty grand, and it kind of stopped me cold."
      },
      {
        "who": "you",
        "text": "I appreciate you saying it out loud, most people just sit on that. So - I'm not the one who quotes the final number; the doctor builds that after he sees your scan, and it depends a lot on your bone and whether you'd need any grafting. What I can promise is the consult is free, it includes the 3D scan, and that's the visit where you get a real number and a real timeline for April - not a guess off a website."
      },
      {
        "who": "lead",
        "text": "Yeah, that's way better. That website number was making me spiral a little."
      },
      {
        "who": "you",
        "text": "Totally normal. And honestly a lot of folks are surprised how different it looks once it's their actual mouth on the screen instead of a headline. So let's get you in front of the doctor. Since you travel Tuesday to Thursday - I've got this Friday at 9:15, or next Monday at 4:30. Which one keeps you on track for April?"
      },
      {
        "who": "lead",
        "text": "Friday's tight, I don't land till Thursday night. Let's do Monday at 4:30."
      },
      {
        "who": "you",
        "text": "Monday 4:30, done. It's about an hour - scan, sit with the doctor, walk out with your plan and your number. I'll text you the address and a quick pre-visit note. Can I use this number you're calling from?"
      },
      {
        "who": "lead",
        "text": "Yep, this is my cell."
      },
      {
        "who": "you",
        "text": "Perfect. Monday at 4:30 it is - and hey, tuck that April date in the back of your mind, because that's exactly what we're building toward. We'll take great care of you."
      },
      {
        "who": "lead",
        "text": "Thank you - this already feels better than I expected walking in."
      }
    ]
  },
  {
    "persona": "Terrified of the pain and recovery",
    "band": "low",
    "booked": false,
    "narrative": "She handed you her exact fear twice — the drilling and her sister's two-week swelling — and instead of sitting with it you reassured past it, dropped \"a few thousand\" with nothing in front of it, and let her leave with an email and an \"I'll think about it.\"",
    "wins": [
      "You were honest about insurance instead of overselling — saying 'most plans don't cover implants great, they treat it as elective' keeps her trust and won't blow up on her at the consult.",
      "You kept a warm, no-pressure tone the whole way through, so she never got defensive or hung up early."
    ],
    "misses": [
      "She told you the real 'why' twice — the needles/drilling and her sister being swollen and in pain for two weeks — and you answered with 'everybody heals different,' never once naming or validating the fear.",
      "You said 'it can be a few thousand for a single tooth' with zero value in front of it, so the number landed naked and she immediately recoiled with 'oof.'",
      "You closed by offering to email info and telling her to 'call back whenever you're ready' — no specific consult times were ever offered, so nothing got booked."
    ],
    "phrases": [
      {
        "from": "Oh, everybody heals different. Two weeks is probably on the longer end. You'd probably be fine in a few days.",
        "to": "That thing with your sister sounds genuinely scary, and I don't blame you for it being stuck in your head. That's exactly the kind of thing the doctor walks through with you — what YOUR recovery looks like and what he does to keep swelling down."
      },
      {
        "from": "It can be a few thousand for a single tooth. But the doctor would give you the exact number at the consult.",
        "to": "Fair question. What you're really paying for is one tooth you never have to think about again instead of a bridge that keeps failing you — the doctor prices it out exactly at the consult, and that visit is free with no commitment."
      },
      {
        "from": "Do you want me to email you some info about the implant process? And then whenever you're ready you can call back and we'll get you in.",
        "to": "Here's what I'd do — let's get you in for the free consult so you can throw every pain question you've got straight at the doctor. I've got Thursday at 10 or Friday at 2 — which one's easier for you?"
      }
    ],
    "nextScenario": "Next, try a skeptical spouse-decision lead who's already collected two quotes elsewhere and cuts off every reassurance with \"just tell me the number.\"",
    "transcript": [
      {
        "who": "lead",
        "text": "Hi, um... I saw online you guys do the implant thing? I've been meaning to call for like a month but honestly I keep chickening out and hanging up. Is it — is it as bad as everybody makes it sound?"
      },
      {
        "who": "you",
        "text": "Oh, hi! Yeah, we do implants all the time. So honestly it's really not that bad, most people do totally fine. Were you looking at like a single tooth, or the whole arch kind of thing?"
      },
      {
        "who": "lead",
        "text": "One tooth. Back on the bottom, it cracked forever ago and I've got this temporary bridge thing that's failing now. My old dentist said implant, but then he retired and I just... froze. I don't do well with dental stuff. Needles, the drilling sound, all of it — I get really worked up."
      },
      {
        "who": "you",
        "text": "Okay, yeah, no, that's super common, don't worry. So the good news is the actual placement's pretty quick, we get you all numbed up, you won't feel much at all. A lot of our patients say it's easier than a filling, honestly."
      },
      {
        "who": "lead",
        "text": "See, that's the thing, everybody says that. But how long am I actually out of it after? Because I can't take a bunch of time off work, and my sister had one done and she was swollen up for like two weeks and in a ton of pain. That's kind of what's been living in my head, you know?"
      },
      {
        "who": "you",
        "text": "Oh, everybody heals different. Two weeks is probably on the longer end. You'd probably be fine in a few days. We can go over all that stuff later."
      },
      {
        "who": "lead",
        "text": "Okay. And I mean, I hate to even ask, but — roughly what does something like this run? I don't want to get all the way in and then find out there's no way I can afford it."
      },
      {
        "who": "you",
        "text": "So it kind of depends. There's the implant itself, the post, the crown, and sometimes if you need a bone graft it's a little more. It can be a few thousand for a single tooth. But the doctor would give you the exact number at the consult."
      },
      {
        "who": "lead",
        "text": "A few thousand. Oof. Yeah. And my insurance is pretty basic, so I'm guessing it doesn't cover much of that."
      },
      {
        "who": "you",
        "text": "Yeah, honestly most plans don't cover implants great, they kind of treat it as elective. Some cover a little of the crown part sometimes. We could always check for you."
      },
      {
        "who": "lead",
        "text": "Right. I don't know. It's a lot of money, and the pain thing is really what's stopping me if I'm being honest. Part of me is just thinking maybe I keep limping along with the temporary bridge."
      },
      {
        "who": "you",
        "text": "I totally get it. I mean, the implant's the better long-term option for sure, the bridge stuff does fail eventually like you said. But it's your call, no pressure at all."
      },
      {
        "who": "lead",
        "text": "Yeah. I think I just need to sit with it a bit more."
      },
      {
        "who": "you",
        "text": "Totally, no rush. Um, do you want me to just email you some info on the implant process? And then whenever you're ready you can call back and we'll get you scheduled. And seriously, don't stress about the pain part, it's really not bad. Have a good one!"
      }
    ]
  }
];

/** Pick a call whose band matches the score, cycling by index for variety. */
export function pickCall(overall: number, index: number): DemoCall {
  const band = overall < 3.6 ? "low" : overall > 4.2 ? "high" : "mid";
  const pool = CALL_LIBRARY.filter((c) => c.band === band);
  const list = pool.length ? pool : CALL_LIBRARY;
  return list[Math.abs(index) % list.length];
}

/** Build an ElevenLabs-shaped post-call payload from a call's transcript (what
 *  getSessionResult reads to render the "Listen back" transcript). */
export function transcriptPayload(call: DemoCall, durationSec: number) {
  const n = call.transcript.length;
  const transcript = call.transcript.map((t, i) => ({
    role: t.who === "you" ? "user" : "agent",
    message: t.text,
    time_in_call_secs: Math.max(1, Math.round(((i + 1) / (n + 1)) * durationSec)),
  }));
  return { data: { transcript } };
}
