// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (real values), then .env as a fallback. dotenv does not
// override already-set vars, so .env.local wins. On Vercel, process.env is
// already populated and these files are absent — both are fine.
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use a direct connection (Supabase pooler can't run DDL).
    // The app runtime uses DATABASE_URL (pooled) via the pg driver adapter.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
